### ISSUE TITLE
Cannot use import statement

### ISSUE THREAD

**Issue by markolofsen** [rouftom/react-mui-scheduler#1]
```bash
frontend/node_modules/react-mui-scheduler/dist/index.esm.js:1
import _defineProperty from '@babel/runtime/helpers/defineProperty';
^^^^^^
```

**Comment by rouftom** [comment]
Hello @markolofsen,

Can you provide more information about the outcome you have? For example the operating system, the version of nodejs, the framework used or the procedure for reproducing the bug.
