### ISSUE TITLE
Korean translation issue

### ISSUE THREAD

**Issue by BennieKim** [rouftom/react-mui-scheduler#13]
Thanks for your efforts.

The followed is some wrong...
{
  "day": "낮",
  "week": "주",
  "month": "월",
  "timeline": "타임라인",
  "mon": "월",
  "tue": "화요일",
  "wed": "수",
  "thu": "목",
  "fri": "금",
  "sat": "앉았다",
  "sun": "해",
  "search": "검색..."
}

I would like to suggest the real Korean. 
{
  "day": "일",
  "week": "주",
  "month": "월",
  "timeline": "타임라인",
  "mon": "월",
  "tue": "화",
  "wed": "수",
  "thu": "목",
  "fri": "금",
  "sat": "토",
  "sun": "일",
  "search": "검색..."
}

and Korean don't use "." at date like "MON." Because it is not abbreviation.
That is, '화' is OK but not '화.'

I really appreciate everything you’ve done.

**Comment by rouftom** [comment]
Hello @BennieKim,

Thanks for the suggestion, i will update the project.
