### ISSUE TITLE
Is it possible to localize the displayed text?

### ISSUE THREAD

**Issue by WachsenHaus** [rouftom/react-mui-scheduler#2]
Hello, I am using the library you shared.

I'm trying to make a simple project. I want to display the displayed text in Korean(ex. monday -> 월요일 ), but what should I do?

Thanks for sharing a good library

**Comment by rouftom** [comment]
Hello @WachsenHaus, for the moment, the library is only available in English, but I will integrate internationalization in future versions.

**Comment by rouftom** [comment]
Hi @WachsenHaus,

internationalization will be available in the next release which will be published shortly.
