### ISSUE TITLE
Rendering bug of months starting on sunday

### ISSUE THREAD

**Issue by PeterWadie** [rouftom/react-mui-scheduler#3]
![image](https://drive.google.com/uc?export=view&id=1msvjjMcrdIoqZqZHfTq4rQSuzrBM8Cue)
![image](https://drive.google.com/uc?export=view&id=1zjvc9m7qk-QsbX5Lizz62lp7R3_pNgcK)

Hello @rouftom,

As you can see from both images that the first of May is shifted by one day and therefore all days after.
The issue is weird because it happens only in May 2022.

Thanks.

**Comment by rouftom** [comment]
Hi @PeterAbdalla,

Thanks for the report. I fixed the problem, I will release a new version with bug fixes and other improvements.

**Comment by PeterWadie** [comment]
![image](https://drive.google.com/uc?export=view&id=1OeKAaP-7Xum70v9nxnPpcviOblEbH1cP)
![image](https://drive.google.com/uc?export=view&id=1OLyDqfpXdD31WTrT0s-v4pOJ4LWnJLp6)

Hello @rouftom,

As you can see from both images above, the older styling looks much better. Can we have it back or at least extend column border lines to the end of the table?
Also, the new bug is that not all days of the month are shown at a time. You need to go to June to view the last two days of May.

Thanks a lot.

**Comment by rouftom** [comment]
Hi @PeterAbdalla,

😁 Don't worry, I found that too. I am in the process of redesigning the library (style and internationalization). However, the old style will still be available (for example using a property legacyStyle={true}).
Here's a preview, what do you think?

![FireShot Capture 464 - React Material Scheduler - localhost](https://user-images.githubusercontent.com/12144793/165832161-b565b68f-944c-4314-abe3-7ea9dc8d354f.png)
