### ISSUE TITLE
Demo code not working?

### ISSUE THREAD

**Issue by manuargue** [rouftom/react-mui-scheduler#4]
Hello. I created an empty project, install `react-mui-scheduler`, and copy-paste the example in the readme to give it a try, but it fails to run the app with error:
![image](https://user-images.githubusercontent.com/511857/166140930-98480a1d-435b-4c6a-968d-d9b5c539f707.png)

There seems to be some problems with the dependencies:
```
> mkdir test
> cd test
> npm init
> npm install --save react-mui-scheduler
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @mui/x-date-pickers@5.0.0-alpha.0
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   peer react@">=16.8.0" from @emotion/react@11.9.0
npm WARN   node_modules/@emotion/react
npm WARN     @emotion/react@"^11.8.2" from react-mui-scheduler@2.0.0
npm WARN     node_modules/react-mui-scheduler
npm WARN     4 more (@emotion/styled, @mui/material, @mui/system, @mui/styled-engine)
npm WARN   13 more (@emotion/styled, @mui/icons-material, @mui/material, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^17.0.2" from @mui/x-date-pickers@5.0.0-alpha.0
npm WARN node_modules/@mui/x-date-pickers
npm WARN   @mui/x-date-pickers@"5.0.0-alpha.0" from @mui/lab@5.0.0-alpha.79
npm WARN   node_modules/@mui/lab
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^17.0.2" from @mui/x-date-pickers@5.0.0-alpha.0
npm WARN   node_modules/@mui/x-date-pickers
npm WARN     @mui/x-date-pickers@"5.0.0-alpha.0" from @mui/lab@5.0.0-alpha.79
npm WARN     node_modules/@mui/lab
```
Could you please help me to take a look? The component seems great btw! Thanks

**Comment by rouftom** [comment]
Hello @manuargue,

The library was developed upstream of React, did you install react in your project before installing react-mui-scheduler ?

**Comment by manuargue** [comment]
Yes, sorry I forgot to mention that. I've also tried creating an app from scratch with `npx create-react-app ./test` and then `npm i --save react-mui-scheduler` inside `./test`. The warnings during npm install and errors during app launch are the same as reported above. My `package.json` after creating the barebones react app contains:
```json
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.1.1",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
```
Perhaps would be useful to have a codepen or similar with the sample code. Would it be too much trouble to create one?

**Comment by rouftom** [comment]
Here is a demo: https://codesandbox.io/s/relaxed-neumann-174pod?file=/src/App.js

Do not hesitate to reopen the issue if you have a problem.

**Comment by jameskirkpatrick23** [comment]
So to be sure I understand this. I need to uninstall react, and uninstall this package. Then reinstall this package. Then reinstall react?
